Java 21 upgrade with Spring Boot 3
companieshouse/confirmation-statement-api pull request #314
Opened 2024-06-20 13:11 UTC by zrahman-ch

2024-07-31 13:26 UTC, dgurjar-ch commented on src/main/resources/application.properties
>  management.endpoints.web.path-mapping.health=/confirmation-statement-api/healthcheck
Please remove one back slace (/) from base path mapping  .
Like  management.endpoints.web.path-mapping.health=confirmation-statement-api/healthcheck

2024-07-31 13:34 UTC, dgurjar-ch commented on pom.xml
> +                        <image>169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/confirmation-statement-api:latest</image>
I don't "local" is required, Can you please check. Also I think we should have  will similar image for java and application "416670754337" and same region west-2

2024-07-31 13:39 UTC, dgurjar-ch commented on README.md
> +- [Java 21](https://www.oracle.com/java/technologies/downloads/#java11)
Please update link as well for java 21, it points to java11

2024-07-31 14:04 UTC, foman-ch requested changes

2024-07-31 14:04 UTC, foman-ch commented on pom.xml
>          <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
there's a newer version

2024-07-31 14:04 UTC, foman-ch commented on pom.xml
>          <spring-boot-maven-plugin.version>2.7.18</spring-boot-maven-plugin.version>
upgrade to 3.3.1

2024-07-31 14:04 UTC, foman-ch commented on pom.xml
>          <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
upgrade this and the compiler

2024-08-01 09:23 UTC, foman-ch approved these changes

2024-08-01 10:05 UTC, foman-ch commented
@aduffy-ch you might want to check why the analyse-pull-request on the pipeline wasn't triggered by this PR

2024-08-01 14:02 UTC, merged