Tech debt - 885
companieshouse/confirmation-statement-api pull request #326
Opened 2024-11-01 17:26 UTC by aduffy-ch

https://companieshouse.atlassian.net/browse/JU-885

update springboot version & other dependencies
remove healthcheck from lb path

2024-11-01 17:27 UTC, ch-code-analysis commented
CI: IaC Security warnings found!

2024-11-22 14:26 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-11-25 12:25 UTC, ch-code-analysis commented
CI: IaC Security warnings found!

2024-11-25 13:22 UTC, foman-ch requested changes

2024-11-25 13:22 UTC, foman-ch commented on terraform/groups/ecs-service/locals.tf
>    lb_listener_paths          = ["/transactions/*/confirmation-statement/*", "/confirmation-statement/*", "/private/confirmation-statement/*", "/private/transactions/*/confirmation-statement/*/filings
think it's this line that you need to remove the healtcheck from, in order for it not to be picked up by the load balancer

2024-11-25 13:22 UTC, foman-ch commented on terraform/groups/ecs-service/locals.tf
> +  healthcheck_path           = "/confirmation-statement-api"
keep this line the same - the container will still need the healthcheck to be defined as:/confirmation-statement-api/healthcheck

2024-11-25 13:48 UTC, ch-code-analysis commented
CI: IaC Security warnings found!

2024-11-25 13:50 UTC, ch-code-analysis commented
CI: IaC Security warnings found!

2024-11-25 15:39 UTC, merged