Feature/dvop 3123 confirmation statement api ecs terraform update
companieshouse/confirmation-statement-api pull request #328
Opened 2024-12-04 13:36 UTC by cryder-ch

2024-12-04 13:36 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-16 14:03 UTC, ch-code-analysis commented
CI: No IaC security warnings found

2024-12-17 12:02 UTC, makhtar-ch commented on terraform/groups/ecs-service/main.tf
> +  min_task_count                     = var.min_task_count
On line 84 of this file, I'd remove read_only_root_filesystem = false, as the latest module update should address this.

2024-12-17 12:40 UTC, makhtar-ch requested changes

2025-01-23 11:29 UTC, makhtar-ch approved these changes

2025-01-23 11:32 UTC, merged